on:
  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  build-worker:
    name: Build Worker
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GH_PAT }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      CLOUDFLARE_API_KEY: ${{ secrets.CLOUDFLARE_API_KEY }}
      CLOUDFLARE_KV_NAMESPACE_ID: ${{ secrets.CLOUDFLARE_KV_NAMESPACE_ID }}

    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.13

      - name: Check out
        uses: actions/checkout@v3

      - name: Install Node Dependencies
        working-directory: workers/strava
        run: npm install

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_KEY }}
          workingDirectory: workers/strava
          command: deploy
